### ISSUE TITLE
Error nested-item

### ISSUE THREAD

**Issue by glbatistabh** [lolmaus/ember-drag-sort#78]
Hello. Can you help me? My model has sub-levels (nested list) and when running the "nested-item" example it gives an error: _"Uncaught (in promise) TypeError: Cannot read properties of null (reading 'syscall')"_

#### error
```
runtime.js:2003 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'syscall')
    at AppendOpcodes.evaluate (runtime.js:2003:1)
    at LowLevelVM.evaluateSyscall (runtime.js:4906:1)
    at LowLevelVM.evaluateInner (runtime.js:4862:1)
    at LowLevelVM.evaluateOuter (runtime.js:4854:1)
    at JitVM.next (runtime.js:5798:1)
    at TemplateIteratorImpl.next (runtime.js:5927:1)
    at RootState.render (index.js:8771:1)
    at runInAutotrackingTransaction (validator.js:102:1)
    at index.js:9069:1
    at inTransaction (runtime.js:1959:1)
```
![Captura de tela de 2022-09-02 12-20-20](https://user-images.githubusercontent.com/8257020/188181638-e8ce1d6c-c03e-4538-8f43-277c67fc7655.png)

#### my environment
```
node: 14.15.5
ember-cli: 3.15.2
os: Ubuntu 22.04.1 LTS (linux x64)
```

#### process
```
ember new test-drag-drop
cd test-drag-drop
ember i ember-drag-sort
ember generate controller index
ember generate template index
```

#### test-drag-drop/app/controllers/index.js
```
import Controller from '@ember/controller';
import { action } from "@ember/object";
import { tracked } from "@glimmer/tracking";
import {A} from '@ember/array'

export default class IndexController extends Controller {

  @tracked
  nestedItem = {
    name: 'start',
    children: A([
      {
        name: "A",
        children: A([
          {name: "A1", children: A([])},
          {name: "A2", children: A([])},
          {name: "A3", children: A([])}
        ])
      }, {
        name: "B",
        children: A([
          {name: "B1", children: A([])},
          {name: "B2", children: A([])},
          {name: "B3", children: A([])}
        ])
      }, {
        name: "C",
        children: A([
          {name: "C1", children: A([])},
          {name: "C2", children: A([])},
          {name: "C3", children: A([])}
        ])
      }
    ])
  };

  @action
  dragEnd( {sourceList, sourceIndex, targetList, targetIndex}) {

    if (sourceList === targetList && sourceIndex === targetIndex)
      return;

    const item = sourceList.objectAt(sourceIndex);

    sourceList.removeAt(sourceIndex);
    targetList.insertAt(targetIndex, item);
  }
}
```

#### test-drag-drop/app/templates/index.hbs
```
{{nested-item
    item          = nestedItem
    dragEndAction = (action 'dragEnd')
}}
```

**Comment by glbatistabh** [comment]
problem solved
